services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AIRO
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
