spring:
  application:
    name: "airo-local"
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

server:
  port: 9001
  servlet:
    context-path: /api